[project]
name = "greatmarsh-sensors"
version = "0.1.0"
description = "Add a short description here"
authors = ["mrahnis <mrahnis@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
pandas = ">=2.2.1,<2.3"
matplotlib = ">=3.8.3,<3.9"
jupyterlab = ">=4.2.4,<4.3"
notebook = ">=7.2.1,<7.3"
openpyxl = ">=3.1.4,<4"
pyarrow = ">=15.0.2,<16"
